### PR TITLE
Use argparse instead of optparse

### PR DESCRIPTION
**Pull request by toabctl**
optparse is deprecated[1] so use argparse.

[1] https://docs.python.org/3/library/optparse.html

### CODE REVIEW

**Comment by toabctl** [comment]
@Oneiroi any comments?

**Comment by Oneiroi** [comment]
@toabctl thank you for this PR, my comments are the tool has not at this time been ported to Python3 thus the deprecation (after 3.2 as I read the docs) it not relevant to this tool.

However I will agree with Python 2.x being deprecated from Jan 1 2020 this needs to move to Python 3 compatible and this change in that respect makes sense.

I'll need to carry out further testing to ensure compatibility, then will merge, thank you once again for this PR.

**Comment by toabctl** [comment]
@Oneiroi let me know if I can do anything else to move this forward. I think what would be really useful are unit and integration tests that could be executed via travis or so..

**Comment by toabctl** [comment]
rebased ...

**Comment by toabctl** [comment]
Oh. This rebase was wrong. So argparse is **not** used....

**Comment by Oneiroi** [comment]
Fixed in #29

**Pull request merged**
