### PR TITLE
Handle closed connections

### PR DESCRIPTION
**Pull request by jhesketh**
If ha-proxy health check or some other program closes its connection before a result is returned an exception is raised when writing to the socket. This wasn't being caught causing do_GET to end prematurely and not finish its clean up. This meant that the db conn was still open and the being_updated flag was checked thus stopping any future requests updating the cache.

In other words, all future requests would return the same old cache result once one bad request is closed mid way.

This fixes the above issue which I think is also related to #16

### CODE REVIEW

**Comment by Oneiroi** [comment]
Hi @jhesketh,

Thanks for this submission, code looks good to me. 
Please note the issues addressed here are also fixed in the `twisted` implementation available here: https://github.com/Oneiroi/clustercheck/tree/twisted

The version in master still runs SimpleHTTPServer this in itself has issues which lead to performance degradation I discussed these in a blog post available here: https://www.percona.com/blog/2014/05/16/benchmark-simplehttpserver-vs-pyclustercheck-twisted-implementation/

As we have to allow for older OS's we can not (yet) merge the twisted branch into master, I would encourage you to use it however if you are able to do so as the performance is by far most consistent than that of the SimpleHTTPServer implementation.

**Comment by jhesketh** [comment]
Thanks! I'll take a look at the twisted branch.

(It's off topic for this PR, but since you're around, would you mind addressing https://github.com/Oneiroi/clustercheck/issues/17 please? We'll need to know the license of this repo).

**Comment by Oneiroi** [comment]
Done added GNUv3 here https://github.com/Oneiroi/clustercheck/blob/master/LICENSE

**Comment by jhesketh** [comment]
Awesome, thanks!

**Pull request merged**
