### PR TITLE
Add clustercheck to console_scripts and fix pep8 style checks

### PR DESCRIPTION
**Pull request by toabctl**
When installing clustercheck via pip, the clustercheck executable
should be installed into the bin path. Use the entry_points
console_scripts mechanism for that.

### CODE REVIEW

**Comment by toabctl** [comment]
cc @Oneiroi

**Comment by toabctl** [comment]
@Oneiroi are you on IRC (or any other real-time communication platform) so we could discuss a couple of things?

**Comment by Oneiroi** [comment]
I'm on Freenode as `Oneiroi` in a handful of channels, #fedora #rhel just joined #suse

**Comment by Oneiroi** [comment]
Also on keybase; https://keybase.io/oneiroi fwiw :)

**Pull request merged**
