### PR TITLE
Add a standard setup.py file

### PR DESCRIPTION
**Pull request by toabctl**
Add a standard setup.py file[1] so the clustercheck script/module can
be distributed on pypi[2] similar to other python modules.

This has a couple of advantages:
- module is distributable on pypi
- module can be installed in a virtual environment
- standard mechanisms for distribution (like creating a sdist source
  tarball) are used so downstream packagers can pick up the package
  easily
- the script has a clear version based on the SCM (try "python
setup.py --version")

[1] https://docs.python.org/3/distutils/setupscript.html
[2] https://pypi.org/

### CODE REVIEW

**Comment by toabctl** [comment]
@Oneiroi friendly ping for a review

**Comment by Oneiroi** [comment]
LGTM, thanks!

**Comment by toabctl** [comment]
@Oneiroi I plan to upload the sdist tarball to pypi. Do you have an pypi account so I can add you as maintainer, too? Or any reason to **not** upload it to pypi yet?

**Comment by Oneiroi** [comment]
Just registered as Oneiroi, no issues I am aware of with uploaded too PyPi
so please feel freew to go ahead, thanks!

**Pull request merged**
